#define MD5_LEN 32
#define SEG_SIZE 512
#define SEG_DIR "../res/"
#define SEG_PATH "../res/segment_"
#define FILE_PATH "../res/"
#define SYN_FILE_PATH "../res/syn/"
#define SYN_FILE_PATH "../res/syn/"
#define SERVER_FILE_PATH  "../res/server/"
#define CLIENT_FILE_PATH "../res/client/"
